// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrJ-nE9mfqlDfYIJB3ee-ymzEoKgaCO08',
    appId: '1:732923680645:web:a17163d8ad8af7163ad6ec',
    messagingSenderId: '732923680645',
    projectId: 'contact-with-me-e90d0',
    authDomain: 'contact-with-me-e90d0.firebaseapp.com',
    storageBucket: 'contact-with-me-e90d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCj4Xx8QfTfMXjMv5ywSwYGXq-pY9Y24I',
    appId: '1:732923680645:android:ad2f375cc4de36a93ad6ec',
    messagingSenderId: '732923680645',
    projectId: 'contact-with-me-e90d0',
    storageBucket: 'contact-with-me-e90d0.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrJ-nE9mfqlDfYIJB3ee-ymzEoKgaCO08',
    appId: '1:732923680645:web:75b57f1c5d4b48783ad6ec',
    messagingSenderId: '732923680645',
    projectId: 'contact-with-me-e90d0',
    authDomain: 'contact-with-me-e90d0.firebaseapp.com',
    storageBucket: 'contact-with-me-e90d0.appspot.com',
  );
}
